@startuml

title __VIEW's Class Diagram__\n

  namespace  {
    namespace t.polimi.ingsw.client {
      namespace view {
        interface it.polimi.ingsw.client.view.ClientInterface {
            {abstract} + anotherPlayerHasBuilt()
            {abstract} + anotherPlayerHasEndedHisTurn()
            {abstract} + anotherPlayerHasMoved()
            {abstract} + anotherPlayerHasPickedUpGod()
            {abstract} + anotherPlayerHasPlacedWorker()
            {abstract} + anotherPlayerHasSelectedGods()
            {abstract} + anotherPlayerHasSelectedWorker()
            {abstract} + anotherPlayerIsBuilding()
            {abstract} + anotherPlayerIsMoving()
            {abstract} + anotherPlayerIsPickingUpGod()
            {abstract} + anotherPlayerIsPlacingWorker()
            {abstract} + anotherPlayerIsSelectingWorker()
            {abstract} + askIpAddress()
            {abstract} + askNumbOfPlayer()
            {abstract} + askUserName()
            {abstract} + build()
            {abstract} + builtSuccessfully()
            {abstract} + choseActionToPerform()
            {abstract} + closeClient()
            {abstract} + debug()
            {abstract} + endBuildRequestError()
            {abstract} + endBuildingPhase()
            {abstract} + endMoveRequestError()
            {abstract} + endMovingPhase()
            {abstract} + endTurn()
            {abstract} + errorWhileActivatingPower()
            {abstract} + errorWhileBuilding()
            {abstract} + errorWhileChoosingGods()
            {abstract} + errorWhileMovingWorker()
            {abstract} + errorWhilePickingUpGod()
            {abstract} + errorWhilePlacingYourWorker()
            {abstract} + errorWhileSelectingWorker()
            {abstract} + godPickedUpSuccessfully()
            {abstract} + godsSelectedSuccessfully()
            {abstract} + iLose()
            {abstract} + loginError()
            {abstract} + loginSuccessful()
            {abstract} + moveWorker()
            {abstract} + pickFromChosenGods()
            {abstract} + placeWorker()
            {abstract} + placingPhaseEnding()
            {abstract} + playerLeftTheGame()
            {abstract} + powerActivated()
            {abstract} + printCanBuildAgain()
            {abstract} + printCanMoveAgain()
            {abstract} + selectGods()
            {abstract} + selectWorker()
            {abstract} + showAllPlayersInGame()
            {abstract} + showDeck()
            {abstract} + showMap()
            {abstract} + someoneElseDoingStuff()
            {abstract} + someoneHasLost()
            {abstract} + startingPlayerTurn()
            {abstract} + startingTurn()
            {abstract} + wantBuildAgain()
            {abstract} + wantMoveAgain()
            {abstract} + workerMovedSuccessfully()
            {abstract} + workerPlacedSuccessfully()
            {abstract} + workerSelectedSuccessfully()
            {abstract} + youAreNotTheGodLikePlayer()
            {abstract} + youAreTheGodLikePlayer()
            {abstract} + youLose()
            {abstract} + youWin()
        }
      }
    }
  }
  

  namespace  {
    namespace t.polimi.ingsw.client {
      namespace view {
        abstract class it.polimi.ingsw.client.view.ClientView {
            + ClientView()
        }
      }
    }
  }
  

  it.polimi.ingsw.client.view.ClientView .up.|> it.polimi.ingsw.client.view.ClientInterface
  it.polimi.ingsw.client.view.ClientView .up.|> java.lang.Runnable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
