@startuml

title __UTILITY's Class Diagram__\n

  namespace  {
    namespace t.polimi.ingsw.utility {
      class it.polimi.ingsw.utility.Ansi {
          {static} + BACKGROUND_BLACK : String
          {static} + BACKGROUND_BLUE : String
          {static} + BACKGROUND_CYAN : String
          {static} + BACKGROUND_GREEN : String
          {static} + BACKGROUND_MAGENTA : String
          {static} + BACKGROUND_RED : String
          {static} + BACKGROUND_WHITE : String
          {static} + BACKGROUND_YELLOW : String
          {static} + BLACK : String
          {static} + BLINK : String
          {static} + BLUE : String
          {static} + BgBlack : Ansi
          {static} + BgBlue : Ansi
          {static} + BgCyan : Ansi
          {static} + BgGreen : Ansi
          {static} + BgMagenta : Ansi
          {static} + BgRed : Ansi
          {static} + BgWhite : Ansi
          {static} + BgYellow : Ansi
          {static} + Black : Ansi
          {static} + Blink : Ansi
          {static} + Blue : Ansi
          {static} + Bold : Ansi
          {static} + CYAN : String
          {static} + Cyan : Ansi
          {static} + GREEN : String
          {static} + Green : Ansi
          {static} + HIGH_INTENSITY : String
          {static} + HighIntensity : Ansi
          {static} + INVISIBLE_TEXT : String
          {static} + ITALIC : String
          {static} + Italic : Ansi
          {static} + LOW_INTENSITY : String
          {static} + LowIntensity : Ansi
          {static} + MAGENTA : String
          {static} + Magenta : Ansi
          {static} + Normal : Ansi
          {static} + RAPID_BLINK : String
          {static} + RED : String
          {static} + REVERSE_VIDEO : String
          {static} + RapidBlink : Ansi
          {static} + Red : Ansi
          {static} + SANE : String
          {static} + UNDERLINE : String
          {static} + Underline : Ansi
          {static} + WHITE : String
          {static} + White : Ansi
          {static} + YELLOW : String
          {static} + Yellow : Ansi
          - codes : String[]
          - codes_str : String
          + Ansi()
          + and()
          + colorize()
          + format()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
