@startuml

title __ENUM's Class Diagram__\n

  namespace  {
    namespace t.polimi.ingsw.network {
      namespace message {
        namespace Enum {
          enum Dispatcher {
            SETUP_GAME
            TURN
          }
        }
      }
    }
  }
  

  namespace  {
    namespace t.polimi.ingsw.network {
      namespace message {
        namespace Enum {
          enum MessageStatus {
            ERROR
            OK
          }
        }
      }
    }
  }
  

  namespace  {
    namespace t.polimi.ingsw.network {
      namespace message {
        namespace Enum {
          enum RequestContent {
            BUILD
            CHECK
            CHOSE_GODS
            END_BUILD
            END_MOVE
            END_TURN
            LOGIN
            MOVE
            NUM_PLAYER
            PICK_GOD
            PLACE_WORKER
            POWER_BUTTON
            SELECT_WORKER
            description
          }
        }
      }
    }
  }
  

  namespace  {
    namespace t.polimi.ingsw.network {
      namespace message {
        namespace Enum {
          enum ResponseContent {
            BUILD
            BUILD_AGAIN
            CHECK
            CHOOSE_GODS
            DISCONNECT
            END_BUILD
            END_MOVE
            END_TURN
            LOGIN
            MOVE_WORKER
            MOVE_WORKER_AGAIN
            NOT_YOUR_TURN
            NUM_PLAYER
            PICK_GOD
            PLACE_WORKER
            PLAYER_HAS_LOST
            PLAYER_HAS_WON
            POWER_BUTTON
            SELECT_WORKER
            SHOW_DECK
            START_TURN
            description
            follows
          }
        }
      }
    }
  }
  

  namespace  {
    namespace t.polimi.ingsw.network {
      namespace message {
        namespace Enum {
          enum ServerRequestContent {
            BUILD
            CHOOSE_GODS_SERVER_REQUEST
            END_TURN
            MOVE_WORKER
            PICK_GOD
            PLACE_WORKER
            SELECT_WORKER
            START_TURN
          }
        }
      }
    }
  }
  

  namespace  {
    namespace t.polimi.ingsw.network {
      namespace message {
        namespace Enum {
          enum UpdateType {
            BUILD
            MOVE
            PLACE
          }
        }
      }
    }
  }
  

  it.polimi.ingsw.network.message.Enum.ResponseContent o-- it.polimi.ingsw.network.message.Enum.RequestContent : follows


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
